require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TxnsController do

  # This should return the minimal set of attributes required to create a valid
  # Txn. As you add validations to Txn, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { date: Date.today }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TxnsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all txns as @txns" do
      txn = Txn.create! valid_attributes
      get :index, {}, valid_session
      assigns(:txns).should eq([txn])
    end
  end

  describe "GET show" do
    it "assigns the requested txn as @txn" do
      txn = Txn.create! valid_attributes
      get :show, {:id => txn.to_param}, valid_session
      assigns(:txn).should eq(txn)
    end
  end

  describe "GET new" do
    it "assigns a new txn as @txn" do
      get :new, {}, valid_session
      assigns(:txn).should be_a_new(Txn)
    end
  end

  describe "GET edit" do
    it "assigns the requested txn as @txn" do
      txn = Txn.create! valid_attributes
      get :edit, {:id => txn.to_param}, valid_session
      assigns(:txn).should eq(txn)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Txn" do
        expect {
          post :create, {:txn => valid_attributes}, valid_session
        }.to change(Txn, :count).by(1)
      end

      it "assigns a newly created txn as @txn" do
        post :create, {:txn => valid_attributes}, valid_session
        assigns(:txn).should be_a(Txn)
        assigns(:txn).should be_persisted
      end

      it "redirects to the created txn" do
        post :create, {:txn => valid_attributes}, valid_session
        response.should redirect_to(Txn.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved txn as @txn" do
        # Trigger the behavior that occurs when invalid params are submitted
        Txn.any_instance.stub(:save).and_return(false)
        post :create, {:txn => {  }}, valid_session
        assigns(:txn).should be_a_new(Txn)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Txn.any_instance.stub(:save).and_return(false)
        post :create, {:txn => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested txn" do
        txn = Txn.create! valid_attributes
        # Assuming there are no other txns in the database, this
        # specifies that the Txn created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Txn.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => txn.to_param, :txn => { "these" => "params" }}, valid_session
      end

      it "assigns the requested txn as @txn" do
        txn = Txn.create! valid_attributes
        put :update, {:id => txn.to_param, :txn => valid_attributes}, valid_session
        assigns(:txn).should eq(txn)
      end

      it "redirects to the txn" do
        txn = Txn.create! valid_attributes
        put :update, {:id => txn.to_param, :txn => valid_attributes}, valid_session
        response.should redirect_to(txn)
      end
    end

    describe "with invalid params" do
      it "assigns the txn as @txn" do
        txn = Txn.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Txn.any_instance.stub(:save).and_return(false)
        put :update, {:id => txn.to_param, :txn => {  }}, valid_session
        assigns(:txn).should eq(txn)
      end

      it "re-renders the 'edit' template" do
        txn = Txn.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Txn.any_instance.stub(:save).and_return(false)
        put :update, {:id => txn.to_param, :txn => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested txn" do
      txn = Txn.create! valid_attributes
      expect {
        delete :destroy, {:id => txn.to_param}, valid_session
      }.to change(Txn, :count).by(-1)
    end

    it "redirects to the txns list" do
      txn = Txn.create! valid_attributes
      delete :destroy, {:id => txn.to_param}, valid_session
      response.should redirect_to(txns_url)
    end
  end

end
